"""Add adult_count children_count items to payments

Revision ID: 1006edd9653a
Revises: 3e4b067da2d3
Create Date: 2026-06-21 08:52:32.213081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '1006edd9653a'
down_revision: Union[str, None] = '3e4b067da2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.alter_column('artifact_relations', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.drop_column('artifacts', 'image_urls')
    op.drop_column('artifacts', 'thumbnail_url')
    op.drop_column('artifacts', 'image_embedding')
    op.add_column('payments', sa.Column('adult_count', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('children_count', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('items', sa.Text(), nullable=True))
    op.execute("UPDATE payments SET adult_count = ticket_quantity, children_count = 0 WHERE adult_count IS NULL")
    op.alter_column('payments', 'adult_count', nullable=False)
    op.alter_column('payments', 'children_count', nullable=False)
    op.drop_column('payments', 'ticket_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('ticket_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("UPDATE payments SET ticket_quantity = adult_count WHERE ticket_quantity IS NULL")
    op.alter_column('payments', 'ticket_quantity', nullable=False)
    op.drop_column('payments', 'items')
    op.drop_column('payments', 'children_count')
    op.drop_column('payments', 'adult_count')
    op.add_column('artifacts', sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('artifact_relations', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
